In [2]:
# table logika AND 2 input
"""

x1    x2    y
1     1     1
1     0     0
0     1     0
0     0     0

"""

'\n\nx1    x2    y\n1     1     1\n1     0     0\n0     0     0\n0     0     0\n\n'

In [3]:
# machine learning

import keras
import numpy as np

# model
model = keras.Sequential([keras.layers.Dense(units=1, input_shape=[2])])

# compile
model.compile(optimizer='sgd', loss='mean_squared_error')

In [4]:
# set data
xs = np.array([[1,1], [1,0], [0,1], [0,0]], dtype=int)
ys= np.array([1,0,0,0], dtype=int)

In [5]:
# tampilkan arsitektur awal
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 3         
                                                                 
Total params: 3 (12.00 Byte)
Trainable params: 3 (12.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [6]:
# cek bobot model awal
weights = model.get_weights()
weights

# output: array 0 (bobot x, y), array 1 (bias)

[array([[-0.86726075],
        [ 1.2430838 ]], dtype=float32),
 array([0.], dtype=float32)]

In [15]:
# training
model.fit(xs, ys, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 11ms/step - loss: 0.2480
Epoch 2/100
1/1 [==============================] - 0s 10ms/step - loss: 0.2463
Epoch 3/100
1/1 [==============================] - 0s 13ms/step - loss: 0.2445
Epoch 4/100
1/1 [==============================] - 0s 8ms/step - loss: 0.2427
Epoch 5/100
1/1 [==============================] - 0s 9ms/step - loss: 0.2410
Epoch 6/100
1/1 [==============================] - 0s 9ms/step - loss: 0.2393
Epoch 7/100
1/1 [==============================] - 0s 11ms/step - loss: 0.2376
Epoch 8/100
1/1 [==============================] - 0s 9ms/step - loss: 0.2359
Epoch 9/100
1/1 [==============================] - 0s 10ms/step - loss: 0.2343
Epoch 10/100
1/1 [==============================] - 0s 9ms/step - loss: 0.2326
Epoch 11/100
1/1 [==============================] - 0s 8ms/step - loss: 0.2310
Epoch 12/100
1/1 [==============================] - 0s 9ms/step - loss: 0.2294
Epoch 13/100
1/1 [==============================] - 0s 8

In [16]:
# test
data = [1, 1]
answer = model.predict([data])
print(answer)

1/1 [==============================] - 0s 38ms/step
[[0.63973147]]


In [17]:
# cek bobot model akhir
weights = model.get_weights()
weights

[array([[0.01436185],
        [0.71489906]], dtype=float32),
 array([-0.08952948], dtype=float32)]

# Usecase

In [18]:
# table data
"""
w1 = 2
w2 = 4

x1    x2    y
2     3     16
4     1     12
5     4     28
7     5     34
8     2     24

"""

'\nw1 = 2\nw2 = 4\n\nx1    x2    y\n2     3     16\n4     1     12\n5     4     28\n7     5     34\n8     2     24\n\n'

In [21]:
# model
model2 = keras.Sequential([keras.layers.Dense(units=1, input_shape=[2])])

# model compile
model2.compile(optimizer='sgd', loss='mean_squared_error')

# set data
xs = np.array([[2,3], [4,1], [5,4], [7,5], [8,2]], dtype=int)
ys = np.array([16, 12, 28, 34, 24], dtype=int)


In [22]:
# cek bobot model awal

weights = model2.get_weights()
weights

[array([[0.09191346],
        [0.4360354 ]], dtype=float32),
 array([0.], dtype=float32)]

In [28]:
# training
model2.fit(xs, ys, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 12ms/step - loss: 0.5512
Epoch 2/100
1/1 [==============================] - 0s 10ms/step - loss: 0.5512
Epoch 3/100
1/1 [==============================] - 0s 8ms/step - loss: 0.5512
Epoch 4/100
1/1 [==============================] - 0s 11ms/step - loss: 0.5512
Epoch 5/100
1/1 [==============================] - 0s 8ms/step - loss: 0.5512
Epoch 6/100
1/1 [==============================] - 0s 9ms/step - loss: 0.5512
Epoch 7/100
1/1 [==============================] - 0s 9ms/step - loss: 0.5512
Epoch 8/100
1/1 [==============================] - 0s 9ms/step - loss: 0.5512
Epoch 9/100
1/1 [==============================] - 0s 8ms/step - loss: 0.5512
Epoch 10/100
1/1 [==============================] - 0s 9ms/step - loss: 0.5512
Epoch 11/100
1/1 [==============================] - 0s 10ms/step - loss: 0.5512
Epoch 12/100
1/1 [==============================] - 0s 9ms/step - loss: 0.5512
Epoch 13/100
1/1 [==============================] - 0s 8m

In [29]:
# test
data = [1,3]
answer = model2.predict([data])
print(answer)

# seharusnya 1*2 + 3*4 = 14

1/1 [==============================] - 0s 36ms/step
[[14.616692]]


In [30]:
# cek bobot model akhir
weights = model2.get_weights()
weights

[array([[1.9495513],
        [4.20762  ]], dtype=float32),
 array([0.04428048], dtype=float32)]